assets:
  settings.xml: Minlessika/keys#settings.xml
  public.key: Minlessika/keys#public.key
  private.key: Minlessika/keys#private.key
architect:
  - baudoliver7
merge:
  fast-forward: only
  rebase: true
  script: |
    mvn clean install --errors --settings /home/r/settings.xml
release:
    sensitive:
     - settings.xml
    script: |-
     [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
     gpg --import /home/r/public.key
     gpg --allow-secret-key-import --import --batch --pinentry-mode=loopback /home/r/private.key 
     mvn versions:set "-DnewVersion=${tag}" --settings /home/r/settings.xml
     git commit -am "${tag}"
     mvn clean deploy -Psonatype -Ptakes-utils --errors --settings /home/r/settings.xml
