install: |-
  sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  pdd --file=/dev/null
assets:
  settings.xml: Minlessika/keys#settings.xml
  pubring.kbx: Minlessika/keys#pubring.kbx
architect:
  - baudoliver7
merge:
  fast-forward: only
  rebase: true
  script: |
    mvn clean install --errors --settings /home/r/settings.xml
release:
    pre: false
    sensitive:
     - settings.xml
    script: |-
     [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
     gpg --no-default-keyring --keyring /home/r/pubring.kbx  --export -a | gpg --import
     mvn versions:set "-DnewVersion=${tag}" --settings /home/r/settings.xml
     git commit -am "${tag}"
     mvn clean deploy -Psonatype --errors --settings /home/r/settings.xml
