docker:
  image: g4s8/rultor:alpine3.10
assets:
  settings.xml: Minlessika/keys#settings.xml
  pubring.kbx: Minlessika/keys#pubring.kbx
architect:
  - baudoliver7
merge:
  fast-forward: only
  rebase: true
  script: |
    mvn clean install --errors --settings /home/r/settings.xml
release:
    sensitive:
     - settings.xml
    script: |-
     [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
     gpg --no-default-keyring --keyring /home/r/pubring.kbx  --export -a | gpg --import
     mvn versions:set "-DnewVersion=${tag}" --settings /home/r/settings.xml
     git commit -am "${tag}"
     mvn clean deploy -Psonatype -Ptakes-utils --errors --settings /home/r/settings.xml
