docker:
  image: g4s8/rultor:alpine3.10
assets:
  settings.xml: Minlessika/keys#settings.xml
  pubring.kbx: Minlessika/keys#pubring.kbx
architect:
  - baudoliver7
install: |
  sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
merge:
  script: |
    mvn clean install --errors --settings /home/r/settings.xml
release:
    sensitive:
     - settings.xml
    script: |-
     [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
     gpg --import /home/r/pubring.kbx
     mvn versions:set "-DnewVersion=${tag}" --settings /home/r/settings.xml
     git commit -am "${tag}"
     mvn clean deploy -Psonatype --errors --settings /home/r/settings.xml
