docker:
  image: yegor256/rultor-image:1.3
assets:
  settings.xml: Minlessika/keys#settings.xml
  pubring.kbx: Minlessika/keys#pubring.kbx
architect:
  - baudoliver7
install: |
  sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
merge:
  script: |
    mvn clean install --errors --settings ../settings.xml
    pdd --source=$(pwd) --verbose --file=/dev/null
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Psonar -Psonatype -Dinvoker.skip --errors --settings ../settings.xml
